# Generated by Django 5.0.6 on 2024-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('state', models.CharField(default='InProgress', max_length=10)),
                ('guessed_letters', models.CharField(default='', max_length=100)),
                ('incorrect_guesses', models.IntegerField(default=0)),
            ],
        ),
    ]
