import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import type { Metadata } from "next";
import SessionProvider from "@/lib/SessionProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import Navbar from "@/components/Navbar/Navbar";
import SessionStatus from "@/lib/SessionStatus";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hangman",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  const session = await getServerSession();

  return (
    <html lang={locale}>
      <SessionProvider session={session}>
        <NextIntlClientProvider messages={messages}>
          <ReactQueryProvider>
            <SessionStatus>
              <body className={inter.className} style={{ overflow: "hidden" }}>
                <Toaster position="top-center" reverseOrder={false} />
                <Navbar />
                <div className="flex pt-[3rem]">
                  <main style={{ width: "100%" }}>{children}</main>
                </div>
              </body>
            </SessionStatus>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </SessionProvider>
    </html>
  );
}
